type HousekeeperInformation {
  firstName: String
  lastName: String
  dateOfBirth: String
  nationality: String
  phoneNumber: String
  companyAddress: HousekeeperAddress
}

type HousekeeperInformationEdge {
  node: HousekeeperInformation
  cursor: String!
}

type HousekeeperInformationConnection {
  edges: [HousekeeperInformationEdge]
  pageInfo: PageInfo!
}

type Query {
  housekeeperInformations(
    first: Int
    after: String
  ): HousekeeperInformationConnection
}
