# ---------------------------------------------------------
# Me - logged in user informations
# ---------------------------------------------------------

type MePayload {
  id: String!
  email: String!
  role: String!
}

type Query {
  me: MePayload!
}
